# docker-compose.yml
version: '3.6'

services:
  mariadb:
    container_name: database_mariadb
    image: mariadb:10.10.2
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_HOST: localhost
      TZ: America/Bogota
    command: --default-time-zone='America/Bogota'
    ports:
      - 3306:3306
    volumes:
      - data_mariadb_10_10_2:/var/lib/mysql
volumes:
  data_mariadb_10_10_2:
    external: false
